### ISSUE TITLE
Support latest OZ account version

### ISSUE THREAD

**Issue by notV4l** [xJonathanLEI/starkli#106]
I was trying to `starkli account fetch` a Katana account, but seems latest oz account version is not supported :(
`0x07dc7899aa655b0aae51eadff6d801a58e97dd99cf4666ee59e704249e51adf2 is not a known account class hash.`

**Comment by xJonathanLEI** [comment]
Hmm this is not an official OZ account class hash. If you check you'll find that this class is not declared in public networks - neither Sepolia or Mainnet.

However, it does look like that this class hash matches the `katana` default prefunded account list. Is that what you're trying to do? `katana` uses an effectively-identical account contract as OZ but their hashes are still different due to different fully qualified names.

If so, the upcoming v0.3.6 release (coming out in about an hour) will include the updated list of `katana` accounts (55a1bb47c0bafddad33c319b91ea3d554a86cb71) so that you can do something like:


```console
starkli invoke --account katana ....
```

to use the first prefunded account and `--katana-1` etc. for others.
