### ISSUE TITLE
Error: code=-32603, message="Internal error: StarknetErrorCode.UNDECLARED_CLASS: Class with hash 0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx is not declared."

### ISSUE THREAD

**Issue by shaochila** [xJonathanLEI/starkli#25]
I run the starkli account oz init /a/1 --keystore /k/1 command in the Starkli Book Account deployment step, and this kind of error occurs. What is the problem?
Error: code=-32603, message="Internal error: StarknetErrorCode.UNDECLARED_CLASS: Class with hash 0x48dd59fabc729a5db3afdf649xxxxxxxxxxxxx is not declared."

**Comment by xJonathanLEI** [comment]
What network are you trying this on? Mainnet?

**Comment by shaochila** [comment]
> What network are you trying this on? Mainnet?

The mainnet configured by the JSON-RPC provider used, the account balance is zero，Is it because the balance is zero?

**Comment by xJonathanLEI** [comment]
It's not because of zero account balance. This OZ account class hash simply isn't declared on mainnet, which is causing the issue.

Unless you know what you're doing, using OZ accounts on mainnet is not quite recommended, as it's non-upgradeable and will be lost when re-genesis hits, since the account is a Cairo 0 contract.

The latest v0.1.10 release added support for Argent X and Braavos accounts. You might want to check that out.

**Comment by shaochila** [comment]
Awesome, problem solved, thank you
