### ISSUE TITLE
suppress certain warnings for example `using private key in plain text`

### ISSUE THREAD

**Issue by arijoon** [xJonathanLEI/starkli#41]
This warning can be misleading due to use-case. For example in our case, we would like to use our standard encryption and secrets protocol to encrypt our key. During usage this is decrypted and passed to the command in a single step (`starkli --private-key $(decypt-key)`. 

The warning in this case does not apply since the key is not leaked as plaintext in the shell history. Would be appreciated if there was a way to suppress certain warnings that do not apply. Additionally it would be much appreciated if we can pass a `PRIVATE_KEY` environment variable instead since that is a fairly standard method of passing secrets to programs.

**Comment by xJonathanLEI** [comment]
This issue is actually two feature requests:

1. support setting private key via env var
2. option to suppress warnings when using plain text private keys

Feature 1 has actually been requested (and declined) multiple times. I'm still worried about misuse, but at the same time, it's Starkli's goal to also be useful for scripting. So this has just been resolved in https://github.com/xJonathanLEI/starkli/commit/5d27c9095ac4bf3c04021cc4952b8d7701c3929d and will be shipped in the next release.

The environment variable is `STARKNET_PRIVATE_KEY` not `PRIVATE_KEY` though, to avoid clashing with other tools that expect `PRIVATE_KEY` (e.g. `cast`).

**Comment by xJonathanLEI** [comment]
And feature 2 is now also implemented in https://github.com/xJonathanLEI/starkli/commit/f3793783c96c2578e0e56593a0da43d267006778. You can now disable the plain private key warning message by setting the `STARKLI_NO_PLAIN_KEY_WARNING` environment variable.
