### ISSUE TITLE
issue: Declaring and calculating a class hash of a declared class retrieved from a public network

### ISSUE THREAD

**Issue by odednaor** [xJonathanLEI/starkli#53]
After getting a class using `starkli class-by-hash`, when trying to calculate the class hash on that class using `starkli class-hash` or when trying to declare the same class on a different chain using `starkli declare` results in an `Error: failed to parse contract artifact`.

This error is shown for both Cairo 0 and Cairo contracts.

**Comment by xJonathanLEI** [comment]
The issue here is that the JSON-RPC representation of a class is slightly different from what you actually get off the compiler. To solve this exact issue, a new option `--parse` has been added for the `class-by-hash` command (https://github.com/xJonathanLEI/starkli/commit/08b9571029a8860975e1fef6aad17593f18ff1b1). Simply add this option and you'll get the recovered class artifact instead, which looks exactly like the ones you'd get from compiling.

Will close this issue once it's released.

**Comment by xJonathanLEI** [comment]
Released in v0.2.0.

**Comment by learnfortime** [comment]
` starkli declare --account ~/.starkli-wallets/deployer/account.json  target/dev/hellow_world.sierra.json` is declare contract command, but error is `Error: failed to parse contract artifact`, what solution is it ?

**Comment by xJonathanLEI** [comment]
@learnfortime Please open a new issue unless you're in the exact same scenario as OP: trying to declare the result from `class-by-hash`.
