### ISSUE TITLE
This error occurred when I was performing a signature operation on the test network: it is not a known account class hash

### ISSUE THREAD

**Issue by 007-liang** [xJonathanLEI/starkli#70]
```shell
starkli account fetch 0x00622e8eebd020b1b9402f8133736eeecf9754222898af1f3566ecfa121bbefb --rpc https://starknet-testnet.public.blastapi.io/rpc/v0_6  --output ./wallet/goerli/account0_account.json
```

ERROR :
0x00816dd0297efc55dc1e7559020a3a825e81ef734b558f03c83325d4da7e6253 is not a known account class hash. If you believe this is a bug, submit a PR to:
    https://github.com/xJonathanLEI/starkli
Error: unknown class hash: 0x00816dd0297efc55dc1e7559020a3a825e81ef734b558f03c83325d4da7e6253

VERSION：
starkli: 0.2.5 (3e41c01)
scarb 2.5.4 (28dee92c8 2024-02-14)
cairo: 2.5.4 (https://crates.io/crates/cairo-lang-compiler/2.5.4)
sierra: 1.4.0

**Comment by thefool76** [comment]
is there any solution to this? got the same issue

**Comment by glihm** [comment]
Hello guys, yes it's related to the issue #69, once it is added to starkli it will be supported.

You could also try to submit a PR to add the support. ;)

**Comment by xJonathanLEI** [comment]
Hi all. The account being fetched uses the latest Braavos account contract, with supported added in Starkli v0.2.6. Please upgrade by running `starkliup` and this issue will go away.

Btw since you're using the free RPC endpoint from Blast, you can actually utilize Starkli's [free RPC vendor](https://book.starkli.rs/providers#free-rpc-vendors) feature to simplify the command:

```console
starkli account fetch 0x00622e8eebd020b1b9402f8133736eeecf9754222898af1f3566ecfa121bbefb --network goerli  --output ./wallet/goerli/account0_account.json
```

Btw @glihm I'm noticing that lots of people are using the free RPC URLs directly, so I guess this is from some tutorial. Are you aware where this comes from? Might be helpful if we submit a patch there to tell new users to use the feature directly instead.
